language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
install:
  - npm install
  - npm run setup:headless
script:
  - npm run build
  - npm run test
